#!/usr/bin/env python3
# Copyright (c) 2026 The XPChain Core developers
# Distributed under the MIT software license, see the accompanying
# file COPYING or http://www.opensource.org/licenses/mit-license.php.
"""Generate an XPChain exchange-listing fact sheet (JSON or Markdown).

Offline mode uses constants from the reference node sources. Optional --rpc*
flags enrich the sheet with live node version / chain tip data.

Examples:
  ./listing_facts.py --format md > listing-xpc.md
  ./listing_facts.py --format json --chain main
  ./listing_facts.py --datadir ~/.xpchain --format md
"""

from __future__ import annotations

import argparse
import json
import os
import sys
from typing import Any, Dict, List, Optional

_HERE = os.path.dirname(os.path.abspath(__file__))
if _HERE not in sys.path:
    sys.path.insert(0, _HERE)

from rpc import RPCError, connect_from_args  # noqa: E402
from xpc_facts import NETWORKS, listing_fact_sheet  # noqa: E402


def _fetch_live(args: argparse.Namespace) -> Dict[str, Any]:
    rpc = connect_from_args(args)
    chain = rpc.call("getblockchaininfo")
    net = rpc.call("getnetworkinfo")
    live: Dict[str, Any] = {
        "version": net.get("version"),
        "subversion": net.get("subversion"),
        "protocolversion": net.get("protocolversion"),
        "chain": chain.get("chain"),
        "blocks": chain.get("blocks"),
        "headers": chain.get("headers"),
        "bestblockhash": chain.get("bestblockhash"),
        "verificationprogress": chain.get("verificationprogress"),
        "initialblockdownload": chain.get("initialblockdownload"),
    }
    try:
        w = rpc.call("getwalletinfo")
        live["wallet"] = {
            "walletname": w.get("walletname"),
            "balance": w.get("balance"),
            "immature_balance": w.get("immature_balance"),
            "txcount": w.get("txcount"),
            "unlocked_until": w.get("unlocked_until"),
            "databaseformat": w.get("databaseformat"),
            "sqlcipher": w.get("sqlcipher"),
        }
    except RPCError:
        live["wallet"] = None
    return live


def render_markdown(sheet: Dict[str, Any]) -> str:
    a = sheet["asset"]
    u = sheet["units"]
    n = sheet["network"]
    addr = sheet["addresses"]
    node = sheet["node_requirements"]
    dw = sheet["deposit_withdrawal"]
    lines: List[str] = []
    lines.append("# XPChain (XPC) Exchange Listing Fact Sheet")
    lines.append("")
    lines.append("Auto-generated by `contrib/exchange/listing_facts.py`.")
    lines.append("Authoritative integration notes: `doc/exchange-integration.md`.")
    lines.append("")
    lines.append("## Asset")
    lines.append("")
    lines.append("| Field | Value |")
    lines.append("|-------|-------|")
    lines.append("| Name | %s |" % a["name"])
    lines.append("| Ticker | %s |" % a["ticker"])
    lines.append("| Website | %s |" % a["website"])
    lines.append("| Source | %s |" % a["source_repository"])
    lines.append("| Consensus | %s |" % a["consensus"])
    lines.append("| Codebase | %s |" % a["implementation_base"])
    lines.append("")
    lines.append("## Units")
    lines.append("")
    lines.append("| Field | Value |")
    lines.append("|-------|-------|")
    lines.append("| Decimals | **%d** |" % u["decimals"])
    lines.append("| Base units per coin | %d |" % u["base_units_per_coin"])
    lines.append("| Valid example | `%s` |" % u["example_valid"])
    lines.append("| Invalid example | `%s` |" % u["example_invalid"])
    lines.append("| Max supply (coins) | %s |" % u["max_supply_coins"])
    lines.append("")
    lines.append("## Network (%s)" % n["display_name"])
    lines.append("")
    lines.append("| Field | Value |")
    lines.append("|-------|-------|")
    lines.append("| Block time | ~%ss |" % n["block_time_seconds"])
    lines.append("| P2P port | %s |" % n["p2p_port"])
    lines.append("| RPC port | %s |" % n["rpc_port"])
    lines.append("| Magic bytes | `%s` |" % n["magic_bytes_hex"])
    lines.append("| Genesis | `%s` |" % (n["genesis_hash"] or "see node"))
    lines.append("| Coinbase/stake maturity | %s blocks |" % n["coinbase_maturity_blocks"])
    lines.append("| Suggested confirmations | %s |" % n["recommended_confirmations"])
    if n["dns_seeds"]:
        lines.append("| DNS seeds | %s |" % ", ".join(n["dns_seeds"]))
    lines.append("")
    lines.append("## Addresses")
    lines.append("")
    lines.append("| Field | Value |")
    lines.append("|-------|-------|")
    lines.append("| Recommended type | %s |" % addr["recommended_type"])
    lines.append("| Bech32 HRP | `%s` |" % addr["bech32_hrp"])
    lines.append("| Example prefix | `%s` |" % addr["example_prefix"])
    lines.append("| Support address length up to | %s chars |" % addr["recommended_max_length"])
    lines.append("")
    for note in addr["notes"]:
        lines.append("- %s" % note)
    lines.append("")
    lines.append("## Node / wallet requirements")
    lines.append("")
    lines.append("- Daemon: `%s`, CLI: `%s`" % (node["daemon"], node["cli"]))
    lines.append("- Hot wallet flags: `%s`" % "`, `".join(node["hot_wallet_flags"]))
    lines.append("- Encryption: %s" % node["wallet_encryption"])
    lines.append("- Required RPCs: `%s`" % "`, `".join(node["required_rpcs"]))
    lines.append("")
    lines.append("## Deposits & withdrawals")
    lines.append("")
    lines.append("- Detect deposits via: `%s`" % "`, `".join(dw["deposit_detection"]))
    lines.append("- Withdraw with: `%s`" % "`, `".join(dw["withdrawal"]))
    lines.append("- Fee estimate: `%s`" % dw["fee_estimation"])
    lines.append("- Credit categories: `%s`" % "`, `".join(dw["credit_categories"]))
    lines.append("- Ignore categories: `%s`" % "`, `".join(dw["ignore_categories"]))
    lines.append("")
    lines.append("## Critical warnings")
    lines.append("")
    for w in sheet["warnings"]:
        lines.append("- %s" % w)
    lines.append("")
    if sheet.get("live_node"):
        live = sheet["live_node"]
        lines.append("## Live node snapshot")
        lines.append("")
        lines.append("```json")
        lines.append(json.dumps(live, indent=2, sort_keys=True))
        lines.append("```")
        lines.append("")
    lines.append("## Documentation")
    lines.append("")
    for k, v in sheet["documentation"].items():
        lines.append("- %s: `%s`" % (k, v))
    lines.append("")
    return "\n".join(lines)


def main(argv: Optional[List[str]] = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--chain", choices=sorted(NETWORKS.keys()), default="main")
    parser.add_argument("--format", choices=("json", "md", "markdown"), default="md")
    parser.add_argument("--rpcconnect", default="127.0.0.1")
    parser.add_argument("--rpcport", type=int)
    parser.add_argument("--rpcuser")
    parser.add_argument("--rpcpassword")
    parser.add_argument("--datadir", help="Read RPC cookie from this datadir")
    parser.add_argument(
        "--live",
        action="store_true",
        help="Query a running node (implied when --datadir/--rpcuser is set)",
    )
    args = parser.parse_args(argv)

    live = None
    want_live = args.live or args.datadir or args.rpcuser is not None
    if want_live:
        try:
            live = _fetch_live(args)
        except Exception as e:
            print("warning: live node query failed: %s" % e, file=sys.stderr)

    sheet = listing_fact_sheet(args.chain, live=live)
    fmt = "md" if args.format == "markdown" else args.format
    if fmt == "json":
        json.dump(sheet, sys.stdout, indent=2, sort_keys=True)
        sys.stdout.write("\n")
    else:
        sys.stdout.write(render_markdown(sheet))
    return 0


if __name__ == "__main__":
    sys.exit(main())
