#ifndef XPCHAIN_CHAINPARAMSSEEDS_H
#define XPCHAIN_CHAINPARAMSSEEDS_H
/**
 * List of fixed seed nodes for the xpchain network
 * AUTOGENERATED by contrib/seeds/generate-seeds.py
 *
 * Each line contains a 16-byte IPv6 address and a port.
 * IPv4 as well as onion addresses are wrapped inside an IPv6 address accordingly.
 */
/*
static SeedSpec6 pnSeed6_main[] = {
};

static SeedSpec6 pnSeed6_test[] = {
};
*/
#endif // XPCHAIN_CHAINPARAMSSEEDS_H
